lou = User.create(name: 'Lou', username: 'lou', email: 'lou@me.com', street_address: '545 S. Euclid Avenue', city: 'Pasadena', zipcode: 91101)
georgia = User.create(name: 'Georgia', username: 'georgia', email: 'georgia@me.com', street_address: '123 Main Street', city: 'Los Angeles', zipcode: 90210)

product_1 = Product.create(name: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', description: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday', listing_type: 'sell', price: 109.95, total_available: 10, image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg', user: lou)
product_2 = Product.create(name: 'Mens Casual Premium Slim Fit T-Shirts', description: 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.', listing_type: 'sell', price: 22.30, total_available: 10, image: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg', user: lou)
product_3 = Product.create(name: 'Mens Cotton Jacket', description: 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.', listing_type: 'sell', price: 59.99, total_available: 10, image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg', user: lou)
product_4 = Product.create(name: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet", description: "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection", listing_type: 'sell', price: 695, total_available: 10, image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg', user: georgia)
product_5 = Product.create(name: 'WD 2TB Elements Portable External Hard Drive - USB 3.0 ', description: 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system', listing_type: 'sell', price: 64, total_available: 10, image: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg', user: georgia)
product_6 = Product.create(name: 'Rain Jacket Women Windbreaker Striped Climbing Raincoats', description: "Lightweight perfect for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.", listing_type: 'sell', price: 39.99, total_available: 10, image: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg', user: georgia)


